spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.jyccyhkdlpddrkiclpjj.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Ilovemyfriend@1}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.main.allow-bean-definition-overriding=true
server.port=8080

# Logging
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate.SQL=INFO
